# Generated by Django 2.2 on 2021-05-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_book_app', '0002_book_favorite_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='message',
        ),
    ]
