# Generated by Django 2.2 on 2021-05-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0003_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
