# Generated by Django 2.2 on 2021-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='users',
            name='lasttname',
            field=models.CharField(default=2, max_length=45),
            preserve_default=False,
        ),
    ]
