# Generated by Django 2.2 on 2021-04-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20210415_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
