# Generated by Django 2.2 on 2021-04-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20210422_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='description_id',
        ),
    ]
