# Generated by Django 2.2 on 2021-04-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_auto_20210422_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description_id',
            new_name='description',
        ),
    ]
